// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("QuadTree")>]
[<assembly: AssemblyProductAttribute("QuadTree")>]
[<assembly: AssemblyDescriptionAttribute("Provide a QuadTree structure")>]
[<assembly: AssemblyVersionAttribute("0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "QuadTree"
    let [<Literal>] AssemblyProduct = "QuadTree"
    let [<Literal>] AssemblyDescription = "Provide a QuadTree structure"
    let [<Literal>] AssemblyVersion = "0.1"
    let [<Literal>] AssemblyFileVersion = "0.1"
