// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("QuadTree")>]
[<assembly: AssemblyProductAttribute("QuadTree")>]
[<assembly: AssemblyDescriptionAttribute("Provide a QuadTree structure")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "QuadTree"
    let [<Literal>] AssemblyProduct = "QuadTree"
    let [<Literal>] AssemblyDescription = "Provide a QuadTree structure"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
